image: Visual Studio 2017

platform:
  - x64

init:
  - git config --global core.autocrlf input

environment:
  matrix:

    - channel: stable
      target: x86_64-pc-windows-msvc

cache:
  - .cargo -> rust-%channel%-date, cargo-%channel%-build

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - cargo install tauri-cli

build_script:
  - cargo tauri build

test: off

artifacts:
  - path: dist\crmbar-tauri*setup.exe
    name: Setup

  - path: dist\crmbar-tauri*.msi
    name: Setup-msi

  - path: dist\crmbar-tauri*.nsis.zip
    name: Setup-nsis-zip

  - path: dist\crmbar-tauri*.msi.zip
    name: Setup-msi-zip

  - path: dist\crmbar-tauri*.nsis.zip.sig
    name: Setup-nsis-zip-sig

  - path: dist\crmbar-tauri*.msi.zip.sig
    name: Setup-msi-zip-sig

 
