image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:

  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
  # Stable 32-bit MSVC
    - channel: stable
      target: i686-pc-windows-msvc
  # Stable 64-bit GNU
    - channel: stable
      target: x86_64-pc-windows-gnu
  # Stable 32-bit GNU
    - channel: stable
      target: i686-pc-windows-gnu

init:
  - git config --global core.autocrlf input

skip_non_tags: true

cache:
  - C:\Users\appveyor\.cargo\registry
  - src-tauri\target\release\build

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - cargo install tauri-cli

build_script:
  - cargo tauri build

test: off

artifacts:
  - path: src-tauri\target\release\bundle\nsis\crmbar-tauri*setup.exe
    name: Setup

  - path: src-tauri\target\release\bundle\nsis\crmbar-tauri*setup.nsis*
    name: Setup-zip

  - path: src-tauri\target\release\bundle\msi\crmbar-tauri*.msi
    name: Setup-msi

  - path: src-tauri\target\release\bundle\msi\crmbar-tauri*.msi*
    name: Setup-msi-zip

deploy:
  provider: Environment
  name: GitHub Releases crmbar-tauri
