image: Visual Studio 2017

platform:
  - x64

init:
  - git config --global core.autocrlf input

environment:
  matrix:

    - channel: stable
      target: x86_64-pc-windows-msvc

cache:
  - src-tauri/.cargo -> rust-%channel%-date, cargo-%channel%-build

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - cargo install tauri-cli

build_script:
  - cargo tauri build

test: off

artifacts:
  - path: nsis\crmbar-tauri*setup.exe
    name: Setup

  - path: nsis\crmbar-tauri*setup.nsis*
    name: Setup-zip

  - path: msi\crmbar-tauri*.msi
    name: Setup-msi

  - path: msi\crmbar-tauri*.msi*
    name: Setup-msi-zip

 
